### ISSUE TITLE
Can't run prediction and train scripts

### ISSUE THREAD

**Issue by szl0144** [nianticlabs/panoptic-forecasting#3]
Hi,

I successfully download the dataset using the download_data.sh and set up all the dependencies in my conda env. Then I tried to run the prediction and training scripts scripts/fg/run_fg_eval_panoptic.sh and scripts/fg/run_fg_train.sh, and faced the following errors.

python: can't open file 'panoptic_forecasting/experiments/export_cityscapes_segmentation_results.py': [Errno 2] No such file or directory
python: can't open file 'panoptic_forecasting/experiments/train_model.py': [Errno 2] No such file or directory

I check the Github code and didn't find the folder experiments. Can you tell me how I can get the file panoptic_forecasting/experiments/export_cityscapes_segmentation_results.py? Thanks!

Best,
Shaoyi

**Comment by cgraber** [comment]
Due to an error in the gitignore file, two of the code folders were being excluded from commits. I have fixed this and pushed the files that were missing. Please let me know if anything else seems to be missing.

**Comment by szl0144** [comment]
Hi,

Thanks for your swift reply. The training/prediction starts to run but face a file not found error. 
File "/home/ssm-user/panoptic-forecasting/panoptic_forecasting/utils/config.py
I didn't see script downloads this file, can you please help me double check it? Thanks!

Best,
Shaoyi

**Comment by cgraber** [comment]
It looks like this file is in the repo ([here](https://github.com/nianticlabs/panoptic-forecasting/blob/master/panoptic_forecasting/utils/config.py)). Can you double check that this didn't get accidentally deleted somehow?

**Comment by szl0144** [comment]
Got it, sorry I didn't copy the error completely. The missing file is /pretrained_models/bg/config.yaml. This is the full error code.

Traceback (most recent call last):
  File "panoptic_forecasting/experiments/export_cityscapes_segmentation_results.py", line 183, in <module>
    params = load_config(extra_args)
  File "/home/ssm-user/panoptic-forecasting/panoptic_forecasting/utils/config.py", line 57, in load_config
    with open(config_path, 'r') as fin:
FileNotFoundError: [Errno 2] No such file or directory: './pretrained_models/bg/config.yaml'

Thanks!

**Comment by cgraber** [comment]
I see - these files I did forget to upload. They should be there now. Thanks for your patience in getting this all worked out!

**Comment by szl0144** [comment]
Thanks for your patient replies, the error disappears after downloading these two YAML files. But face a new error as following. I think it's related to the dataset gtFine_trainvaltest? Do I need to download that dataset to the path /data02/cgraber2/cityscapes/gtFine/? 

Traceback (most recent call last):
  File "panoptic_forecasting/experiments/export_cityscapes_panoptic_results.py", line 188, in <module>
    params = load_config(extra_args)
  File "/home/ssm-user/panoptic-forecasting/panoptic_forecasting/utils/config.py", line 58, in load_config
    params = yaml.safe_load(fin)
  File "/root/anaconda3/envs/panoptic/lib/python3.7/site-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/root/anaconda3/envs/panoptic/lib/python3.7/site-packages/yaml/__init__.py", line 112, in load
    loader = Loader(stream)
  File "/root/anaconda3/envs/panoptic/lib/python3.7/site-packages/yaml/loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "/root/anaconda3/envs/panoptic/lib/python3.7/site-packages/yaml/reader.py", line 85, in __init__
    self.determine_encoding()
  File "/root/anaconda3/envs/panoptic/lib/python3.7/site-packages/yaml/reader.py", line 124, in determine_encoding
    self.update_raw()
  File "/root/anaconda3/envs/panoptic/lib/python3.7/site-packages/yaml/reader.py", line 178, in update_raw
    data = self.stream.read(size)
  File "/root/anaconda3/envs/panoptic/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
ERROR: Could not find a ground truth json file in /data02/cgraber2/cityscapes/gtFine/cityscapes_panoptic_val.json. Please run the script with '--help'

**Comment by cgraber** [comment]
So there are two errors happening here:

1.  The config file fails to load. My current guess as to what's happening is that the script is being run from the wrong directory. I just updated the README to make this more clear, but scripts should be run from the root project directory, i.e. as `./scripts/fg/run_fg_eval_panoptic`. If you were already doing this, then let me know and I'll keep looking.
2. The line beginning with "ERROR" is from the cityscapes evaluation script. The script specified the wrong GT path locations; this should be fixed now (assuming all cityscapes data is in `data/cityscapes/*`, e.g. the gtFine folder should be `data/cityscapes/gtFine`

**Comment by szl0144** [comment]
Hi,

Thanks! I run the script in the root directory. I also download the gtFine dataset in the path data/cityscapes/. I think the error is because there is no gt-json-file named cityscapes_panoptic_val.json in the gtFine_trainvaltest dataset and no gt folder cityscapes_panoptic_val. Can you tell me where I can get them? I grep the name in the cityscapes dataset but didn't find.

ERROR: Could not find a ground truth json file in data/cityscapes/gtFine/cityscapes_panoptic_val.json. Please run the script with '--help'

**Comment by cgraber** [comment]
Yes, you are right. One step I omitted in the instructions is that the panoptic labels should be generated from the data using the official cityscapes scripts:
`python -m cityscapesscripts.preparation.createPanopticImgs --dataset-folder data/cityscapes/gtFine/`

This will generate the missing file.

**Comment by szl0144** [comment]
Thanks! The previous error disappear, but still lack some files. Can you help me with it?

ERROR: Could not find a prediction json file in ./experiments/pretrained_fg/exported_panoptics_midterm_val/exported_panoptics_midterm_val.json. Please run the script with '--help'

**Comment by cgraber** [comment]
That error happens because the script that exports the panoptic segmentations is failing. Are you getting the same error as before, i.e. the one that ended in `UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte`?

**Comment by szl0144** [comment]
Yes. The error happens before the file not found. Can you give me some hint how to solve it?

**Comment by cgraber** [comment]
Could you add a print statement after [this line](https://github.com/nianticlabs/panoptic-forecasting/blob/master/panoptic_forecasting/utils/config.py#L56) for the variable `config_path` and tell me what you get? The issue is that it's not finding the config file that I pushed to the repo earlier where it should be located.

**Comment by szl0144** [comment]
Hi,
The print statement "Config File Print" shows behind the errors.
![image](https://user-images.githubusercontent.com/40918217/132262436-78ee4a29-42dc-4f8d-92f8-00dc317e6633.png)

**Comment by cgraber** [comment]
Sorry, I wasn't clear enough; what I wanted you to add to that line was something like the following:
`print("CONFIG PATH:", config_path)`

I'm trying to see whether it's looking at the correct path to load the config or not.

**Comment by szl0144** [comment]
Got it, sorry for the misunderstanding. I set the statement and print it again. The config.yaml seems at there.
![image](https://user-images.githubusercontent.com/40918217/132262659-3dc23706-7806-4a86-a618-1fca0494a2a4.png)
![image](https://user-images.githubusercontent.com/40918217/132262689-33d14024-3418-4355-ad86-90a5a3722f60.png)

**Comment by szl0144** [comment]
Hi,

Just redownload the repo to solve the error, thanks! Will continue to solve a dependency error to see the result.

**Comment by szl0144** [comment]
Already solved the dependency issues, but faced a new file not found error 
![image](https://user-images.githubusercontent.com/40918217/132270534-8f36f257-fb6e-418f-ada0-c6319cfcc2ff.png)

Can you please tell me how to get the ./experiments/pretrained_bg/exported_predictions_mid_trainids/val/lindau/lindau_000057_000019_gtFine_labelIds.png'?

**Comment by cgraber** [comment]
I updated the README to make this clearer - the background exporting script must be run before the foreground exporting script can be run (as this script combines the foreground/background predictions). There are a few data preprocessing steps required first; make sure you run the following first if you haven't already done so:
- `CITYSCAPES_DATASET=data/cityscapes/ python -m cityscapesscripts.preparation.createTrainIdLabelImgs` 
- `scripts/preprocessing/remove_fg_from_gt.sh`

After this, run:

`scripts/bg/run_export_bg_val.sh`

**Comment by szl0144** [comment]
Completely make sense, I will run the BG script first to get the FG results. Thanks!

**Comment by szl0144** [comment]
Hi,

Just rerun the predictions and everything goes on well, thanks for all of your helps! Can you also tell me what's path of the panoptic semgnetation predictions results? Thanks!

![image](https://user-images.githubusercontent.com/40918217/132568762-1186b98d-bd88-43a2-97a2-7aaeee5c9ed1.png)

**Comment by szl0144** [comment]
Hi,

Just find the exported path ./experiments/pretrained_fg/exported_panoptics_midterm_val/exported_panoptics_midterm_val. One strange thing is there is no bg segmentation inside it. Will re run the bg prediction to see if can solve the issues
![image](https://user-images.githubusercontent.com/40918217/132577133-67fda028-1431-4cb4-8bc9-abfb82176bdd.png)

**Comment by cgraber** [comment]
~~If you want a visualized version of the panoptic segmentations, add the flag `--viz` to the script, i.e. run the following:~~

**EDIT: There was a code block here, but it was wrong. See below for the actual answer.**


The default output is a specific encoding used by the evaluation script; it won't look right if you look at it as an image.

**Comment by szl0144** [comment]
Hi, 

Thanks, the bg shows up after adding the viz in the scripts.
![image](https://user-images.githubusercontent.com/40918217/132593003-9e256edb-46e8-4c68-8120-261961c34e50.png)
A new error is "Exception: no prediction for the image with id: frankfurt_000001_051516" Confused about how the error happens..
![image](https://user-images.githubusercontent.com/40918217/132593124-b6dbc6b0-de7e-4b9e-8512-2e67f2a37740.png)

**Comment by cgraber** [comment]
Yes, I've updated the README to address this: there's a quirk in the way the export script is currently implemented which causes it to write an incomplete json file if you rerun it without deleting the predictions folder first. This happens because there are a number of sequences which do not contain foreground instances, and so the foreground model is not run on these; the script handles this by checking the folder where results are saved for any missing files, and copying the background predictions as appropriate. However, if the script is re-run, no missing files will be found, which means the generated json file is incomplete.

All of this is to say that this issue can be resolved by deleting the folder `experiments/pretrained_fg/exported_panoptics_midterm_val/` before re-running the export script.

**Comment by szl0144** [comment]
Thanks for your detailed explanation, I didn't face the incomplete json error again and run the fg prediction without errors. After adding the --viz option in both fg and bg eval scripts, the complete panoptic segmentation still doesn't show in the prediction result. Can you help me check it?
The command I run the prediction is:
1. python -m cityscapesscripts.preparation.createPanopticImgs --dataset-folder data/cityscapes/gtFine/
2. CITYSCAPES_DATASET=data/cityscapes/ python -m cityscapesscripts.preparation.createTrainIdLabelImgs
3. scripts/preprocessing/remove_fg_from_gt.sh
4. scripts/bg/run_export_bg_val.sh
5. rm -rf experiments/pretrained_fg/exported_panoptics_*_val/
6. scripts/fg/run_fg_eval_panoptic.sh
I see the result only contains the fg segmentation.

![image](https://user-images.githubusercontent.com/40918217/132609529-83c95c57-e228-4f3e-8799-31d91017aad0.png)

**Comment by cgraber** [comment]
I took another look and it turns out I misremembered the process I used to visualize the panoptic segmentations - there was a second script I ran which handled the visualization. I've added this to the repo, and the `scripts/fg/run_fg_eval_panoptic.sh` script now includes the command to run to visualize results. 

Note that this will also require downloading the `leftImg8bit` dataset from the Cityscapes website if you haven't already done so.

**Comment by szl0144** [comment]
Hi,
Finally get the visual panoptic segments following your help. Really appreciate it and many thanks! Will close the issue if the test running of training is also successful. 
![image](https://user-images.githubusercontent.com/40918217/132769786-1e10b915-5979-4349-a7df-a4e150e56820.png)
